// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartTodo.Data;

namespace SmartTodo.Data.Migrations
{
    [DbContext(typeof(SmartTodoDbContext))]
    partial class SmartTodoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("SmartTodo.Domain.TodoItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateTimeCompleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = "e3649d5c-95e2-4fa1-bed3-976b4442095a",
                            DateTimeCreated = new DateTime(2021, 7, 30, 17, 53, 23, 695, DateTimeKind.Local).AddTicks(4777),
                            IsCompleted = false,
                            Title = "Wash dishes"
                        },
                        new
                        {
                            Id = "524bda5a-3e8b-4814-a601-e56172f95370",
                            DateTimeCompleted = new DateTime(2021, 7, 30, 15, 53, 23, 697, DateTimeKind.Local).AddTicks(4171),
                            DateTimeCreated = new DateTime(2021, 7, 29, 17, 53, 23, 697, DateTimeKind.Local).AddTicks(4139),
                            IsCompleted = true,
                            Title = "Go shopping"
                        },
                        new
                        {
                            Id = "9072e8c2-e00a-4899-8e13-e210de105d8a",
                            DateTimeCreated = new DateTime(2021, 7, 30, 22, 53, 23, 697, DateTimeKind.Local).AddTicks(4478),
                            IsCompleted = false,
                            Title = "Meet friends"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
